//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances.
        /// </summary>
        public static string CategoryAppliances {
            get {
                return ResourceManager.GetString("CategoryAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string CategoryBuy {
            get {
                return ResourceManager.GetString("CategoryBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances infomation.
        /// </summary>
        public static string CategoryDecriptionAppliances {
            get {
                return ResourceManager.GetString("CategoryDecriptionAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy infomation.
        /// </summary>
        public static string CategoryDecriptionBuy {
            get {
                return ResourceManager.GetString("CategoryDecriptionBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic infomation.
        /// </summary>
        public static string CategoryDecriptionElectronic {
            get {
                return ResourceManager.GetString("CategoryDecriptionElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign infomation.
        /// </summary>
        public static string CategoryDecriptionForeignInfomation {
            get {
                return ResourceManager.GetString("CategoryDecriptionForeignInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryDecriptionRoot {
            get {
                return ResourceManager.GetString("CategoryDecriptionRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell infomation.
        /// </summary>
        public static string CategoryDecriptionSell {
            get {
                return ResourceManager.GetString("CategoryDecriptionSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        public static string CategoryElectronic {
            get {
                return ResourceManager.GetString("CategoryElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign infomation.
        /// </summary>
        public static string CategoryForeignInfomation {
            get {
                return ResourceManager.GetString("CategoryForeignInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryRoot {
            get {
                return ResourceManager.GetString("CategoryRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string CategorySell {
            get {
                return ResourceManager.GetString("CategorySell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category parent not valid.
        /// </summary>
        public static string CatParentNotValid {
            get {
                return ResourceManager.GetString("CatParentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidLoginInfomation {
            get {
                return ResourceManager.GetString("InvalidLoginInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last post.
        /// </summary>
        public static string LastPost {
            get {
                return ResourceManager.GetString("LastPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string MenuForum {
            get {
                return ResourceManager.GetString("MenuForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string MenuTopic {
            get {
                return ResourceManager.GetString("MenuTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreaded Topic.
        /// </summary>
        public static string MenuUnReadTopic {
            get {
                return ResourceManager.GetString("MenuUnReadTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id facebook invalid.
        /// </summary>
        public static string MessageIdFacebookNull {
            get {
                return ResourceManager.GetString("MessageIdFacebookNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id token facebook invalid.
        /// </summary>
        public static string MessageIdTokenNull {
            get {
                return ResourceManager.GetString("MessageIdTokenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exists.
        /// </summary>
        public static string NoUserExists {
            get {
                return ResourceManager.GetString("NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register success.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string SearchButtonTitle {
            get {
                return ResourceManager.GetString("SearchButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured topics.
        /// </summary>
        public static string Top10Topics {
            get {
                return ResourceManager.GetString("Top10Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exitst.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
    }
}
